unit DDC.Validate.IsNatural.Test;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework,
  DDC.Validate,
  DDC.Validate.CustomAttribute,
  DDC.Validate.IsNatural,
  System.Rtti;

type
  // Test methods for class TIsNatural

  TestTIsNatural = class(TTestCase)
  strict private
    FIsNatural: TIsNatural;
  public
    const
    COLUMN_NAME: String = 'MyProp';
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure GetErrorMessage;
    procedure IsValidString;
    procedure IsValidCurrency;
    procedure IsValidInteger;
    procedure IsValidZero;
  end;

implementation

uses
  System.SysUtils,
  DDC.Validator.ResourceStrings;



procedure TestTIsNatural.SetUp;
begin
  FIsNatural := TIsNatural.Create(COLUMN_NAME);
end;



procedure TestTIsNatural.TearDown;
begin
  FIsNatural.Free;
  FIsNatural := nil;
end;



procedure TestTIsNatural.GetErrorMessage;
begin
  CheckTrue(FIsNatural.GetErrorMessage = Format(TResourceStringsValidator.RSValidation_IsNatural, [COLUMN_NAME]),
    'Erro ao formatar mensagem');
end;



procedure TestTIsNatural.IsValidCurrency;
var
  AValue: TValue;
begin
  AValue := 0123.4;
  CheckFalse(FIsNatural.isValid(AValue), 'Não é um número natural: ' + AValue.ToString);
end;



procedure TestTIsNatural.IsValidInteger;
var
  AValue: TValue;
begin
  AValue := 1234;
  CheckTrue(FIsNatural.isValid(AValue), 'É um número natural maior que zero: ' + AValue.ToString);
end;



procedure TestTIsNatural.IsValidString;
var
  AValue: TValue;
begin
  AValue := 'abcde';
  CheckFalse(FIsNatural.isValid(AValue), 'Não é um número natural: ' + AValue.ToString);
end;



procedure TestTIsNatural.IsValidZero;
var
  AValue: TValue;
begin
  AValue := 0;
  CheckTrue(FIsNatural.isValid(AValue), 'É um número natural: ' + AValue.ToString);
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTIsNatural.Suite);

end.
